---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress-Core,WordPress-Docs,WordPress-Extra"
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.scss"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.md"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "**.png"
  - "**.jpg"
  - "**.gif"
  - "gulpfile.js"
  - "composer.lock"
  - "phpcs.xml"
  - "**.json"
  - "**.pot"
  - "**.txt"
  - "**.min.js"
  - "**.min.css"
  - "**.dist"
  - "**.sh"
  - "tests/*"
  - "dummy-data/*"
